# Generated by Django 5.1.2 on 2024-10-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_des', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='todo',
        ),
    ]
