# Generated by Django 5.1.2 on 2024-10-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_dept_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='todo title')),
                ('description', models.TextField(max_length=30, verbose_name='descrption')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
