# Generated by Django 5.1.2 on 2024-10-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dept',
            new_name='depts',
        ),
    ]
