# Generated by Django 5.1.2 on 2024-10-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_vegitable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depts',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
