# Generated by Django 5.1.2 on 2024-11-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='DEPARTMENT',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='dep_name',
        ),
        migrations.DeleteModel(
            name='todo',
        ),
        migrations.DeleteModel(
            name='Vegitable',
        ),
        migrations.DeleteModel(
            name='depts',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
