# Generated by Django 5.1.2 on 2024-11-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_delete_booking_delete_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_spec', models.TextField()),
                ('doc_image', models.ImageField(default='defaults_image.jpg', upload_to='doctors')),
            ],
        ),
    ]
