# Generated by Django 5.1.2 on 2024-11-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_on',
        ),
    ]
